dist: xenial
language: java
sudo: false
jdk: openjdk14
install: true
addons:
  sonarcloud:
    organization: "rpeleias-training"
    token:
      secure: $SONAR_TOKEN
script:
  - mvn clean verify sonar:sonar -Pcoverage
cache:
  directories:
    - $HOME/.m2