dist: xenial
language: java
sudo: false
jdk: openjdk14
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: ${SONAR_TOKEN}
script:
  - mvn sonar:sonar -P sonar
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache