dist: xenial
language: java
sudo: false
jdk: openjdk14
install: true
addons:
  sonarcloud:
    organization: "rpeleias-training"
    token:
      secure: "$SONAR_TOKEN"
script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=rpeleias-training_bookstoremanager
cache:
  directories:
    - $HOME/.m2