dist: xenial
language: java
sudo: false
jdk: openjdk14
install: true
addons:
  sonarcloud:
    organization: "rpeleias-training"
    token:
      secure: "$SONAR_TOKEN"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - $HOME/.m2